"""
Interactive setup wizard for ArenaChat.
"""

from __future__ import annotations

import asyncio
import secrets
import sys
from pathlib import Path

from notionchat.account import (
    ArenaAccount,
    create_account_from_cookie,
    parse_browser_cookie,
    save_arena_account,
    validate_arena_cookie,
)
from notionchat.exceptions import NotionChatError

_COOKIE_HELP = """
How to copy your Arena.ai browser cookie:

  1. Log in at https://arena.ai
     (On a VPS: log in from a browser that uses the SAME public IP as the server,
      or set ARENACHAT_PROXY first — cookies may fail trust checks on datacenter IPs.)

  2. Open DevTools (F12) → Application → Cookies → https://arena.ai

  3. Select all cookie rows, or run this in the Console tab:

       copy(document.cookie)

  4. Paste the full string here (must include 'arena-auth-prod-v1').

  Note: You may also need the 'cf_clearance' cookie if Cloudflare protection is active.
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _read_cookie(*, preset: str | None = None) -> str:
    """Read and validate arena cookie from user input."""
    if preset:
        is_valid, error = validate_arena_cookie(preset)
        if not is_valid:
            raise NotionChatError(error, status_code=400)
        return preset.strip()

    _print(_COOKIE_HELP)
    _print()
    while True:
        _print("Paste your Arena cookie (single line), then press Enter:")
        cookie = input("> ").strip()
        is_valid, error = validate_arena_cookie(cookie)
        if is_valid:
            return cookie
        _print(f"  {error}")
        if not _prompt_yes_no("Try again?", default=True):
            raise NotionChatError("Setup cancelled.", status_code=1)


def _generate_api_key() -> str:
    """Generate a random API key."""
    return f"sk-arena-chat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    """Parse an existing .env file."""
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    """Render .env file content."""
    lines = [
        "# Generated by: python -m notionchat setup",
        f"ARENACHAT_API_KEY={values.get('ARENACHAT_API_KEY', '')}",
        f"ARENACHAT_HOST={values.get('ARENACHAT_HOST', '127.0.0.1')}",
        f"ARENACHAT_PORT={values.get('ARENACHAT_PORT', '1995')}",
        f"ARENACHAT_ACCOUNT={values.get('ARENACHAT_ACCOUNT', 'arena_account.json')}",
        f"ARENACHAT_BASE_URL={values.get('ARENACHAT_BASE_URL', 'https://arena.ai/api')}",
        f"ARENACHAT_DEFAULT_MODEL={values.get('ARENACHAT_DEFAULT_MODEL', 'arena-gpt-4o')}",
    ]
    cookie = values.get("ARENA_COOKIE", "").strip()
    if cookie:
        lines.append(f"ARENA_COOKIE={cookie}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    """Write updates to .env file."""
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    account_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    """Print success message."""
    _print()
    _print("Setup complete!")
    _print(f"  Account file : {account_path}")
    if env_written:
        _print(f"  Environment  : {env_path}")
    else:
        _print("  Environment  : (skipped — update .env manually if needed)")
    _print()
    _print("Start the server:")
    _print("  python -m notionchat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print()
    _print(f"  Base URL: http://{host}:{port}/v1")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    cookie: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    write_cookie_to_env: bool | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    """Run the interactive setup wizard."""
    env_path = (env_path or Path(".env")).expanduser()
    account_path = (account_path or Path("arena_account.json")).expanduser()
    write_env = True

    _print("ArenaChat setup")
    _print("===============")
    _print()
    _print("This wizard will:")
    _print("  • validate your Arena.ai browser cookie")
    _print("  • save arena_account.json")
    _print("  • create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    # Read cookie
    cookie_value = _read_cookie(preset=cookie)

    # Create account from cookie
    _print()
    _print("Validating cookie...")
    try:
        account = create_account_from_cookie(cookie_value)
        save_arena_account(account, str(account_path))
        _print(f"  User: {account.user_name or account.user_email or account.user_id}")
        _print(f"  Cookie domain: {account.cookie_domain}")
    except NotionChatError as exc:
        _print(f"Error: {exc}", file=sys.stderr)
        return 1

    # Server settings
    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("ARENACHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("ARENACHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("ARENACHAT_PORT") or "1995"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
        include_cookie = write_cookie_to_env if write_cookie_to_env is not None else True
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)
        if write_cookie_to_env is None:
            include_cookie = _prompt_yes_no(
                "Store ARENA_COOKIE in .env for auto-refresh on startup?",
                default=True,
            )
        else:
            include_cookie = write_cookie_to_env

    # Write .env
    if write_env:
        env_updates: dict[str, str] = {
            "ARENACHAT_API_KEY": resolved_api_key,
            "ARENACHAT_HOST": resolved_host,
            "ARENACHAT_PORT": resolved_port,
            "ARENACHAT_ACCOUNT": account_path.name,
        }
        if include_cookie:
            env_updates["ARENA_COOKIE"] = cookie_value
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        account_path=account_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0
